language: ะก++

os:
   - linux

compiler:
   - gcc
   - clang

env:
   - TARGET_CPU=amd64
   - TARGET_CPU=x86

script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git ls-files test/ | xargs clang-format -i && git diff --exit-code
  - make all && bin/test
