language: cpp

os:
   - linux

compiler:
   - gcc
   - clang

env:
   - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
   - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
   - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
   - TARGET_CPU=x64 BUILD_CONFIGURATION=Release

script:
   - make
