language: cpp

os:
   - linux

compiler:
   - gcc

env:
   - TARGET_CPU=amd64
   - TARGET_CPU=x86

before_script:
  - sudo apt-get install libsfml-dev

script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git ls-files test/ | xargs clang-format -i && git diff --exit-code
  - make all && bin/test
